name = "webksp"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
  { pattern = "ksp.ac.th", custom_domain = true },
  { pattern = "www.ksp.ac.th", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
VITE_APP_URL = "https://ksp.ac.th"
CANONICAL_URL = "https://ksp.ac.th"
GAS_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbx1RpY1-wuslTse_CIDomMq_gOaPp3wgEhTdbXoMq7WMYaY3Zzo4jBlfYEyVNC_TIVmdw/exec"
VITE_GAS_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbx1RpY1-wuslTse_CIDomMq_gOaPp3wgEhTdbXoMq7WMYaY3Zzo4jBlfYEyVNC_TIVmdw/exec"
VITE_ADMIN_EMAIL = "nanthaphat@ksp.ac.th"
GAS_SECRET = "KSP_PANYA_SECRET_2026"
VITE_GAS_SECRET = "KSP_PANYA_SECRET_2026"
GOOGLE_DRIVE_FOLDER_ID = "17ZSTF_q9yal63BK1UdALLsh7MfYlNUdK"
